# .github/workflows/build-static-ffmpeg-fdkaac.yml
name: Build Static FFmpeg with fdk-aac (NixOS compatible)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: ${{ github.workspace }}/build
      INSTALL_DIR: ${{ github.workspace }}/ffmpeg_build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y autoconf automake build-essential cmake git libtool \
            pkg-config texinfo zlib1g-dev libssl-dev nasm yasm

      - name: Clone and build fdk-aac
        run: |
          mkdir -p "$BUILD_DIR"
          cd "$BUILD_DIR"
          git clone --depth 1 https://github.com/mstorsjo/fdk-aac
          cd fdk-aac
          autoreconf -fiv
          ./configure --prefix="$INSTALL_DIR" --disable-shared
          make -j$(nproc)
          make install

      - name: Clone and build statically linked FFmpeg
        run: |
          cd "$BUILD_DIR"
          git clone https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg
          PKG_CONFIG_PATH="$INSTALL_DIR/lib/pkgconfig" ./configure \
            --prefix="$INSTALL_DIR" \
            --pkg-config-flags="--static" \
            --extra-cflags="-I$INSTALL_DIR/include" \
            --extra-ldflags="-L$INSTALL_DIR/lib" \
            --extra-libs="-lpthread -lm" \
            --enable-gpl \
            --enable-nonfree \
            --enable-libfdk_aac \
            --disable-shared \
            --enable-static \
            --disable-debug \
            --disable-doc \
            --disable-ffplay \
            --disable-ffprobe \
            --enable-ffmpeg
          make -j$(nproc)
          make install

      - name: Package static ffmpeg binary
        run: |
          tar -czf static-ffmpeg-fdkaac.tar.gz -C "$INSTALL_DIR/bin" ffmpeg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-ffmpeg-fdkaac
          path: static-ffmpeg-fdkaac.tar.gz
