# .github/workflows/build-static-ffmpeg-musl.yml
name: Build Static FFmpeg with fdk-aac using musl (NixOS-compatible)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PREFIX: ${{ github.workspace }}/static-ffmpeg
      BUILD: ${{ github.workspace }}/build

    steps:
      - name: Checkout (dummy step for repo context)
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y musl musl-dev musl-tools \
            build-essential autoconf automake cmake git libtool pkg-config \
            nasm yasm zlib1g-dev curl tar

      - name: Set musl-gcc as default compiler
        run: |
          echo "CC=musl-gcc" >> $GITHUB_ENV
          echo "CXX=musl-g++" >> $GITHUB_ENV

      - name: Build fdk-aac statically with musl
        run: |
          mkdir -p "$BUILD" && cd "$BUILD"
          git clone --depth=1 https://github.com/mstorsjo/fdk-aac
          cd fdk-aac
          autoreconf -fiv
          ./configure --prefix="$PREFIX" --disable-shared --enable-static CC=musl-gcc
          make -j$(nproc)
          make install

      - name: Build FFmpeg statically with musl and fdk-aac
        run: |
          cd "$BUILD"
          git clone https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg

          export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
          export CFLAGS="-static -I$PREFIX/include"
          export LDFLAGS="-static -L$PREFIX/lib"

          ./configure \
            --prefix="$PREFIX" \
            --pkg-config-flags="--static" \
            --extra-cflags="$CFLAGS" \
            --extra-ldflags="$LDFLAGS" \
            --extra-libs="-lpthread -lm" \
            --enable-gpl \
            --enable-nonfree \
            --enable-libfdk_aac \
            --disable-shared \
            --enable-static \
            --disable-ffplay \
            --disable-ffprobe \
            --enable-ffmpeg

          make -j$(nproc)
          make install

      - name: Inspect and verify static binary
        run: |
          file "$PREFIX/bin/ffmpeg"
          ldd "$PREFIX/bin/ffmpeg" || echo "Statically linked ✔️"

      - name: Package artifact
        run: |
          cd "$PREFIX/bin"
          tar -czf ${{ github.workspace }}/ffmpeg-static-musl.tar.gz ffmpeg

      - name: Upload static ffmpeg
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-static-musl
          path: ffmpeg-static-musl.tar.gz
